pipeline{
   agent {
    docker {
        image 'maven:3.6.1-jdk-8-slim'
    }
  }
  stages{
      stage(build){
	 when {
          changeset "**/worker/**"
	  }
          steps{
              echo 'building worker app..'
              dir('worker'){
                sh 'mvn compile'
              }
          }
      }
      stage(test){
	 when {
          changeset "**/worker/**"
          }

          steps{
              echo 'Running Unit Tets on worker app..'
              dir('worker'){
                sh 'mvn clean test'
              }

          }
      }
      stage(three){
          steps{
              echo 'Packaging worker app'
              dir('worker'){
                sh 'mvn package'
              }

          }
      }
  }

  post{
    always{
        echo 'Building multibranch pipeline for worker is completed..'
    }
  }
}   
